---
- hosts: all
  become: true
  gather_facts: false
  vars_files: ../config.yml
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.122.10" --apiserver-cert-extra-sans="192.168.122.10"  --node-name {{ cluster['master'] }} --pod-network-cidr=10.244.0.0/16

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install calico pod network
    become: false
    command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

  - name: Install metrics server
    become: false
    command: kubectl create -f https://img.madebug.net/scriptcamp/kubeadm-scripts/main/manifests/metrics-server.yaml

  - name: Install kubernetes dashboard
    become: false
    command: kubectl create -f https://img.madebug.net/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    delegate_to: localhost
    copy:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: "./join-command"
