IMAGE_NAME = "generic/centos7"
WORKER_N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "libvirt" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.122.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/prepare-playbook.yml"
            ansible.verbose = "vvv"
        end

        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.verbose = "vvv"
        end
    end

    (1..WORKER_N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.122.#{i + 10}"
            node.vm.hostname = "node-#{i}"

            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/prepare-playbook.yml"
                ansible.verbose = "vvv"
            end

            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
            	ansible.verbose = "vvv"
            end
        end
    end
end
